#!/bin/bash

# vi mode
set editing-mode vi


$if mode=vi

set show-mode-in-prompt on
set vi-ins-mode-string ""
set vi-cmd-mode-string "\1\e[1;31m\2!\1\e[0m\2"

# clear screen mapping

set keymap vi-command
Control-l: clear-screen

set keymap vi-insert
Control-l: clear-screen

$endif
